name: Notebooks

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # This cancels any such job that is still runnning
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install jupyter
        python -m pip install -e .
    - name: Run notebooks
      run: |
        python tests/test_notebooks.py
