name: Notebooks

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # This cancels any such job that is still running
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install graphviz
      run: |
        sudo apt-get install -y graphviz graphviz-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pathos pygraphviz neuron cloud-volume k3d scikit-image
        python -m pip install -e .[test-notebook]
    - name: Run notebooks
      env:
        NEUPRINT_APPLICATION_CREDENTIALS: ${{ secrets.neuprint }}
        INSECT_BRAIN_DB_USER: ${{ secrets.insect_brain_db_user }}
        INSECT_BRAIN_DB_PASSWORD: ${{ secrets.insect_brain_db_password }}
      run: |
        python tests/test_notebooks.py
